development:
  adapter: postgresql
  encoding: utf8
  database: jobs_board_production
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: jobs_board_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: jobs_board_production
  pool: 5
